# Generated by Django 3.2.4 on 2023-11-24 11:47

import json

from django.db import migrations, models

from apps.core.serializers import CitySerializer


def initial_filling_db(apps, schema_editor):
    json_file_path = "/usr/src/app/russian-cities.json"

    with open(json_file_path, "r", encoding="utf-8") as json_file:
        json_data = json.load(json_file)

    serializers = CitySerializer(data=json_data, many=True)
    serializers.is_valid()
    serializers.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("coords", models.JSONField(default=dict, verbose_name="Coords")),
                ("district", models.CharField(max_length=255, verbose_name="District")),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("population", models.IntegerField(verbose_name="Population")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "unique_together": {("name", "subject")},
            },
        ),
        migrations.RunPython(initial_filling_db),
    ]
