# Generated by Django 3.2.4 on 2023-11-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=100, verbose_name="Date")),
                ("date_ts", models.IntegerField(verbose_name="Date TS")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_forecasts",
                        to="core.city",
                        verbose_name="City",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weather forecast",
                "verbose_name_plural": "Weather forecasts",
            },
        ),
        migrations.CreateModel(
            name="WeatherFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temp", models.SmallIntegerField(verbose_name="Temperature (C°)")),
                (
                    "pressure_mm",
                    models.SmallIntegerField(verbose_name="Pressure (mm Hg)"),
                ),
                (
                    "wind_speed",
                    models.SmallIntegerField(verbose_name="Wind speed (m/s)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_fact",
                        to="core.city",
                        verbose_name="City",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weather fact",
                "verbose_name_plural": "Weather facts",
            },
        ),
        migrations.CreateModel(
            name="ForecastPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_name",
                    models.CharField(max_length=100, verbose_name="Part name"),
                ),
                (
                    "temp_min",
                    models.SmallIntegerField(verbose_name="Temperature min (C°)"),
                ),
                (
                    "temp_max",
                    models.SmallIntegerField(verbose_name="Temperature max (C°)"),
                ),
                (
                    "temp_avg",
                    models.SmallIntegerField(verbose_name="Temperature avg (C°)"),
                ),
                (
                    "feels_like",
                    models.SmallIntegerField(verbose_name="Feels like (C°)"),
                ),
                (
                    "condition",
                    models.CharField(max_length=100, verbose_name="Condition"),
                ),
                (
                    "wind_speed",
                    models.SmallIntegerField(verbose_name="Wind speed (m/s)"),
                ),
                (
                    "pressure_mm",
                    models.SmallIntegerField(verbose_name="Pressure (mm Hg)"),
                ),
                ("humidity", models.SmallIntegerField(verbose_name="Humidity (%)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weather_forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_parts",
                        to="core.weatherforecast",
                        verbose_name="Weather forecast",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forecast part",
                "verbose_name_plural": "Forecast parts",
            },
        ),
    ]
